### ISSUE TITLE
[DASHBOARD] el eje Y siempre muestra 0

### ISSUE THREAD

**Issue by eduardo0099** [nanjho/elpis-fe#18]
cuenta: 2222 2222
![image](https://user-images.githubusercontent.com/20383082/41830301-aea384c6-7805-11e8-91bd-59dde5648592.png)

**Comment by nanjho** [comment]
bueno, solo le agregare padding para que soporte hasta 5 cifras, sera sufuciente no?

**Comment by eduardo0099** [comment]
claro crack xd
